### ISSUE TITLE
Dropdown.js Fix

### ISSUE THREAD

**Issue by RyanBosley** [Esri/calcite-maps#122]
Sorry if this is wrong place to mention this but I ran into issue using Dojo Bootstrap (Dropdown.js) and noticed that the version in this repo has a fix:

Line 55
// Fix for not setting dropdown target
 if (target.length < 1) {
     target = [e.target.parentElement];
 } 

Should this not be submitted as a pull request to the Dojo Bootstrap project?

**Comment by alaframboise** [comment]
Well you can but I didn't subclass the project because it looked fairly inactive. I had to fix some other stuff as well so I can take the PR here as I maintain a version of the library with this project.

**Comment by Biboba** [comment]
I think that would be interesting to update the project because now we cannot install dojo-bootstrap with bower as the version does not contain the fix. Or maybe the bower depedency should be removed to avoid confusion ?

Cheers for this nice framework,
