### ISSUE TITLE
Display layer in MapView and SceneView

### ISSUE THREAD

**Issue by triesco** [Esri/calcite-maps#124]
I'm adding a layer on the map but only shows either on MapView or SceneView. Is there a way to display layer on both views?? Thanks!

**Comment by alaframboise** [comment]
Are you using the Designer or a different app?

**Comment by triesco** [comment]
Using the sample in ArcGIS API 4.0 under Boostrap Calcite sample.

**Comment by alaframboise** [comment]
If you are using the stock sample, you need to add the layer to the map for both the mapView and the sceneView. ArcGIS JS 4.0 uses different symbols (2D and 3D) for each view type.

I do this here for the Designer.

https://github.com/Esri/calcite-maps/blob/master/samples/styler/js/panelsettings.js#L826

So add the layer to both maps. It's not much overhead at all.

https://github.com/Esri/calcite-maps/blob/master/samples/arcgis-4.x/arcgis-4.x-2d-3d.html#L199

https://github.com/Esri/calcite-maps/blob/master/samples/arcgis-4.x/arcgis-4.x-2d-3d.html#L215

**Comment by triesco** [comment]
Thanks for the reply. I tried your suggestions and this is what I have so
far. Still cant get it to work. It loads on one but not the other depending
on the order. Also would like to be able to click on the parcel and get the
popup. Any suggestions??

Thanks!!!!

var parcels = new MapImageLayer({
url: "whateverurl/MapServer",
outFields: ["*"]
});

      // Map
      var map = new Map({
        basemap: app.basemap
      });
      app.mapView = new MapView({
        container: "mapViewDiv",
        map: map,
        scale: app.scale,
        center: app.center,
        padding: app.viewPadding,
        ui: {
          components: ["zoom", "compass", "attribution"],
          padding: app.uiPadding
        }
      });


      // Scene
      var mapScene = new Map({
        basemap: app.basemap,
        ground: "world-elevation"
      });
      app.sceneView = new SceneView({
        container: "sceneViewDiv",
        map: mapScene,
        scale: app.scale,
        center: app.center,
        padding: app.viewPadding,
        ui: {
          padding: app.uiPadding
        }
      });

      app.activeView = app.sceneView;

      app.activeView.then(function() {
        app.initialExtent = app.activeView.extent;
      });

      app.sceneView.map.add(parcels);
  app.mapView.map.add(parcels);




On Mon, Jul 25, 2016 at 5:54 PM, Allan Laframboise <notifications@github.com

**Comment by alaframboise** [comment]
If you can throw this in a jsBin it would be helpful.
