### ISSUE TITLE
Attribute table?

### ISSUE THREAD

**Issue by crackernutter** [Esri/calcite-maps#126]
Not an issue per se, but would love some guidance on how I might be able to incorporate an attribute table into this design framework.  Using BorderContainers doesn't really seem to work - the map just takes up the entire page...

<div data-dojo-type="dijit/layout/BorderContainer" data-dojo-props="design:'headline'" style="width:100%; height:100%;">
  <div data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'center', splitter:true" style="height:75%">
  <div class="calcite-map">
    <div id="mapViewDiv" class="calcite-map-absolute"></div>
	
  </div>
  </div>
  <div id="bot" data-dojo-type="dijit/layout/ContentPane" data-dojo-props="region:'bottom', splitter:true" style="height:25%">
<div id="attriubteTable"></div>
</div>
 </div>

**Comment by alaframboise** [comment]
Sorry about the delay. What you can do is create a dedicated menu item and a panel for the table.  Put a div element in the panel-body for the table and create it when the app loads. You can have the panel open at the bottom if you want or like the others; just style it accordingly. Just follow the pattern of adding a menu item and panel and it should be easy.

**Comment by crackernutter** [comment]
Thanks so much!  That was much easier than the way I was trying!  One last question - is there a class that allows for a panel to stay open while other panels are also open?  Rather, a way to have multiple panels open at once (especially if those panels occupy different real estate on the screen)?

**Comment by alaframboise** [comment]
No problem. In the HTML I think you can remove the `dataset` property and that will pull it out of the [auto-open/close code](https://github.com/Esri/calcite-maps/blob/master/lib/js/dojo/calcitemaps.js#L71). You will then need to add your own listener to separately open/close that panel.
