### ISSUE TITLE
I found issues with ArcGIS JS 3.17.

### ISSUE THREAD

**Issue by RoelGarciaRoman** [Esri/calcite-maps#129]
I used example 3.x, but I changed to ArcGIS JS 3.17 and I found issues with dojo-bootstrap [collapse.js, Support.js].

Console errors:

Support.js: 178 Uncaught TypeError: Cannot set property 'display' of undefined
Collapse.js: 148 Uncaught TypeError: Cannot read property 'call' of undefined

Any suggestion?

Thank you.

**Comment by alaframboise** [comment]
Ya something is up with the version of dojo associated with 3.17. Might be missing a dependency. I need to look into it deeper.

**Comment by alaframboise** [comment]
Fixed in #133

**Comment by kevinjonesevans** [comment]
I am receiving the above Support issue with ArcGIS version 3.23
