### ISSUE TITLE
Can I use button instead navbar to show panels?

### ISSUE THREAD

**Issue by RoelGarciaRoman** [Esri/calcite-maps#130]
I want to replace the navbar and use buttons for different panels [Widgets]. Is it possible to do that?

Thank you.

**Comment by alaframboise** [comment]
Should be doable.

Do you need the accordion functionality where just one panel is ever open at a time and the others auto-close when a new one is selected? If so, you should just need to change the selector [here](https://github.com/Esri/calcite-maps/blob/master/lib/js/dojo/calcitemaps.js#L37) to listen to clicks on your buttons and then it will sync up all the panels. Set this when you load the calcite-maps library. 

If you don't need the auto-close functionality, just wire up the buttons to each panel [the standard way](http://getbootstrap.com/javascript/#collapse-example-accordion) using bootstrap. You might need a separate panel container for the non-auto-closing panels.
