### ISSUE TITLE
Can I add calcite-maps responsive to infoWindow(Pop-up)?

### ISSUE THREAD

**Issue by RoelGarciaRoman** [Esri/calcite-maps#137]
Hello,

Problem:
Map.infoWindow is not responsive. 

I want to add responsive like calcite panels, I mean calcite panels are showing really good on different devices and orientation devices, Can I add the same functionality to map.infoWindow (Pop-up)?

Thank you.

**Comment by alaframboise** [comment]
Do you mean for ArcGIS 3.x or 4.x? Either way, you can probably use dojo.place() to put the window anywhere you want, including in one of the panels. You'll probably have to listen for a popup show event and place it each time.
