### ISSUE TITLE
I have issue with fonts loading.

### ISSUE THREAD

**Issue by RoelGarciaRoman** [Esri/calcite-maps#138]
I have issues with fonts loading.

This is console log:

https://fast.fonts.net/dv2/14/2cd55546-ec00-4af9-aeca-4a3cd186da53.woff2?d4…c380973f51046de5905a6750d7b&projectId=9431e9a5-7a6d-4b5f-82be-4d935972de5a 

https://fast.fonts.net/dv2/3/1e9892c0-6927-4412-9874-1b82801ba47a.woff?d44f…c380973f51046de5905a6750d7b&projectId=9431e9a5-7a6d-4b5f-82be-4d935972de5a 

Any suggestion?

**Comment by alaframboise** [comment]
Are you running from file:// or //localhost?

**Comment by RoelGarciaRoman** [comment]
I am running from localhost, I am using calcite-maps and other esri classes.

   <link rel="stylesheet" href="https://js.arcgis.com/3.17/dijit/themes/claro/claro.css">
   <link rel="stylesheet" href="https://js.arcgis.com/3.17/esri/css/esri.css">
  <link rel="stylesheet" href="https://js.arcgis.com/3.16/esri/themes/calcite/dijit/calcite.css">
  <link rel="stylesheet" href="https://js.arcgis.com/3.16/esri/themes/calcite/esri/esri.css">


Thank you.

**Comment by RoelGarciaRoman** [comment]
https://js.arcgis.com/3.17/dijit/themes/claro/claro.css
https://js.arcgis.com/3.17/esri/css/esri.css
https://js.arcgis.com/3.16/esri/themes/calcite/dijit/calcite.css
https://js.arcgis.com/3.16/esri/themes/calcite/esri/esri.css

**Comment by RoelGarciaRoman** [comment]
Hello,

Any suggestion for this issue???


Thank you.

**Comment by alaframboise** [comment]
Are the fonts actually loading but you are just getting console errors? Keep in mind that you can either get the fonts from the calcite-maps build or they come with https://js.arcgis.com/3.16/esri/themes/calcite/dijit/calcite.css too. So you need to determine where the errors are coming from.

```@import url(https://fast.fonts.net/cssapi/9431e9a5-7a6d-4b5f-82be-4d935972de5a.css);@import url(https://fast.fonts.net/cssapi/a2f744b5-a294-49c0-8af9-4599ad0ab33f.css);@import url(https://fast.fonts.net/cssapi/9431e9a5-7a6d-4b5f-82be-4d935972de5a.css);@import url(https://fast.fonts.net/cssapi/a2f744b5-a294-49c0-8af9-4599ad0ab33f.css);@font-face {font-family: 'CalciteWebCoreIcons'; src: url("data:application/x-font-ttf;charset=utf-```

**Comment by RoelGarciaRoman** [comment]
Hello, the errors are coming from calcite-bootstrap.min-v0.2.css.

this sample has the same issues:
http://esri.github.io/calcite-maps/samples/arcgis-3.x/arcgis-3.x.html


Any suggestion?

Thank you.

**Comment by alaframboise** [comment]
Latest build has fonts in a local dir. Should solve your issue.
