### ISSUE TITLE
Bootstrap-sass may be missing from package.json

### ISSUE THREAD

**Issue by dfabulic** [Esri/calcite-maps#139]
Gruntfile.js in copy:bootstrapfonts references ./node_modules/bootstrap-sass, but there is no dependency for it in package.json, so if one installs dependencies using npm, copy:bootstrapfontstask will do nothing. That task works after adding 
"bootstrap-sass": "^3.3.7",
to devDependencies in package.json.

I did not use Bower, so I don't know if bower would install it.

**Comment by alaframboise** [comment]
Should be fine now.
