### ISSUE TITLE
Application view stutter on resize event

### ISSUE THREAD

**Issue by andygup** [Esri/calcite-maps#141]
I noticed when I drag a corner of the browser to resize the window, the entire app's content stutters. It's not a smooth larger => smaller or smaller => larger view size transition.

Reproduced in Chrome Desktop and Safari 10.

**Comment by alaframboise** [comment]
Not sure I see any difference with Calcite Maps and default JS 4.x samples. Let me know if you see something I don't.

https://developers.arcgis.com/javascript/latest/sample-code/get-started-mapview/live/index.html

**Comment by andygup** [comment]
I haven't really seen behavior like this in JS 4 samples, but I also haven't done much if any direct comparison between them.

FWIW, I was live demoing the [Styler app](http://esri.github.io/calcite-maps/samples/styler/styler.html) and the Settings widget was bouncing around like a baby chicken as a grabbed a corner of the browser and resized the window. 

Maybe a video of what I'm seeing is a better approach to demonstrating what I'm seeing: [download .mov screen capture](https://dl.dropboxusercontent.com/u/38391979/stutter.mov)

**Comment by alaframboise** [comment]
Oh wow, never seen this. I'll look into it but would be great if I could repro it.

**Comment by andygup** [comment]
@alaframboise additional info:

- I first saw it in [Mac] Chrome Desktop 53, Chrome Canary 55 and Safari 10. Firefox 48 and 49 don't seem to have the problem.
- If I resize from the lower left hand corner of the browser window the bouncing seems much worse

**Comment by alaframboise** [comment]
Fixed with the core ArcGIS API
