### ISSUE TITLE
IE 10 Support

### ISSUE THREAD

**Issue by wmlrose** [Esri/calcite-maps#143]
Navbar and collapsible panel display appear problematic for IE10. 
Is IE10 support planned or even feasible? Suggestions would be greatly appreciated.
Thanks for this great project. It's been a real pleasure to work from the provided samples.

**Comment by alaframboise** [comment]
Hi Bill. I didn't do much testing in IE10 but I'll do a little more and let you know. Thanks.

**Comment by mestevez01** [comment]
I noticed several issues with IE10. Hopefully you'll have the opportunity to take a look at it soon so that we can use Calcite in a production environment. Thanks!

**Comment by wmlrose** [comment]
Suggest closing since IE10 support ended Jan 2020. 
[https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer](https://support.microsoft.com/en-us/help/17454/lifecycle-faq-internet-explorer)
