### ISSUE TITLE
Styler Mixed Content Error

### ISSUE THREAD

**Issue by apulverizer** [Esri/calcite-maps#144]
The styler app doesn't work (Chrome 52).

`Mixed Content: The page at 'https://esri.github.io/calcite-maps/samples/styler/styler.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://js.arcgis.com/4.0/esri/css/main.css'. This request has been blocked; the content must be served over HTTPS.`

`Mixed Content: The page at 'https://esri.github.io/calcite-maps/samples/styler/styler.html' was loaded over HTTPS, but requested an insecure script 'http://js.arcgis.com/4.0/'. This request has been blocked; the content must be served over HTTPS.`

Should be a simple fix.

**Comment by alaframboise** [comment]
Thanks! I'm plan on pushing a bunch of fixes soon and will include this.

**Comment by Cezus** [comment]
@alaframboise Can you tell me how soon? Can you also tell me what the roadmap is?

**Comment by alaframboise** [comment]
Fixed.
