### ISSUE TITLE
Is it possible to export templates/layout from the styler settings page?

### ISSUE THREAD

**Issue by reyemtm** [Esri/calcite-maps#145]

**Comment by alaframboise** [comment]
You can't really export them, but the the https://github.com/Esri/calcite-maps-styler-template app knows how to import and export most of the config settings to config the app on the fly. Check out the sharing functionality.

**Comment by reyemtm** [comment]
Interesting I'll check that out.

**Comment by alaframboise** [comment]
The Styler template is the way to go to save the state. Closing.
