### ISSUE TITLE
Leaflet sample search box needs tweaking for mobile

### ISSUE THREAD

**Issue by andygup** [Esri/calcite-maps#147]
**Issue 1:** When using the [Leaflet sample](https://esri.github.io/calcite-maps/samples/esri-leaflet/esri-leaflet.html) on mobile, if you select the Search option the search box ends up behind the pull-up menu in both portrait and landscape modes.

**Expected Behavior 1:** I expected the pull-up menu to close as soon as I chose the search option, and I expected the search box to be on top.

**Issue 2:** This is minor, but the 'esri' in the attribution text blurb is offset slightly negative in Safari. On Android + Chrome it seemed okay. 

**Expected Behavior 2:** I expected all text of the attribution to be on the same line.

Screenshot below is iPhone 6s and Safari. Same behavior on Android 6 and Chrome.

![image](https://cloud.githubusercontent.com/assets/510440/22750423/006bbefc-edee-11e6-8b4f-ea70372031d1.png)

**Comment by alaframboise** [comment]
This should all be fixed now in the last update.

**Comment by alaframboise** [comment]
Fixed, closing.
