### ISSUE TITLE
Able to use Calcite maps samples with JS 3.2 but lacking /esri/widgets for example

### ISSUE THREAD

**Issue by stevenvandervalk** [Esri/calcite-maps#152]
Hi!  Big fan of the open source work to make it easier to theme modern maps.  I'd love to use the Calcite theme but require ARCGIS JS 3.2 in order to load my own WMS layers.  (I think that is the correct reading of the JS API documentation regarding WMS...)  However I think I'm unable to use most of the widgets and other classes referenced by the Builder and in the Example in the README as 3.2 lacks those classes? 

E.g. `"esri/widgets/Search"` doesn't exist at `https://developers.arcgis.com/javascript/3/jsapi/`.  Any clarification and advice would be awesome and greatly appreciated!

**Comment by alaframboise** [comment]
Hi there. If you are using ArcGIS JS 3.x, then you should start [with this sample](https://github.com/Esri/calcite-maps/blob/master/samples/arcgis-3.x/arcgis-3.x.html) and add the libraries as necessary. For search the module name is `esri/dijit/Search`.

**Comment by stevenvandervalk** [comment]
Ah. Thanks for pointing that out, the namespace `dijit` went unnoticed!
