### ISSUE TITLE
Can calcite-maps work with Esri widgets

### ISSUE THREAD

**Issue by ezequias** [Esri/calcite-maps#154]
Hello

I would like to know if calcite-maps can work with Esri widgets (measure, filter, attribute table, layer list etc).

Sincerely
Ezequias

**Comment by alaframboise** [comment]
See https://github.com/Esri/calcite-maps/issues/155

**Comment by alaframboise** [comment]
You have to integrate each tool as you need them. Some are menu items while others use panels. Closing.
