### ISSUE TITLE
Widgets in 3.18

### ISSUE THREAD

**Issue by TimPeters** [Esri/calcite-maps#155]
Hy @alaframboise ,

1) I am trying to integrate the LayerList widget in the arcgis-3.x.html but it's not working as expected.
Could you provide some support? My .html is available on [JS Bin](http://jsbin.com/ficatigumu/1/edit?html,output).

![untitled-1](https://cloud.githubusercontent.com/assets/26526622/24084765/461d17e6-0cf9-11e7-909b-ad39b618ecd9.jpg)

2) Could you provide the Measurement widget in your arcgis-3.x.html? 
I am struggling with this one as well.

Thank you for your support, 
Tim.

**Comment by alaframboise** [comment]
The 3.x doc indicates that the LayerList widget is not supported with the calcite.css theme.

https://developers.arcgis.com/javascript/3/jshelp/css.html

```
This theme is in beta and does not support all components of the API. The following widgets are supported:

BasemapGallery
BasemapToggle
Bookmarks
Directions
HomeButton
LayerSwipe
Legend
LocateButton
Measurement
OverviewMap
Popup
Print
ScaleBar
Search
```

**Comment by alaframboise** [comment]
To get it to load and at least render you need to pull in the .css manually for that component. With a few other background and border overrides you should be able to get to render nicely with Calcite Maps.

  
  <link rel="stylesheet" href="https://js.arcgis.com/3.20/esri/themes/calcite/esri/esri.css">
  <link rel="stylesheet" href="https://js.arcgis.com/3.20/esri/themes/calcite/dijit/calcite.css">
  
  <link rel="stylesheet" href="https://js.arcgis.com/3.20/esri/dijit/LayerList/css/LayerList.css">

**Comment by TimPeters** [comment]
LayerList widget now working, just needs a litlle css background.
Thank you @alaframboise  !

**Comment by ezequias** [comment]
@TimPeters post a sample here please.

**Comment by TimPeters** [comment]
Hi @ezequias ,

Here is a [JS Bin](http://jsbin.com/sikuyepixi/1/edit?html,output) with the sample code.

**Comment by ezequias** [comment]
Thank you very much @TimPeters but the LayerListWidget is much more than that.

**Comment by tmcgee** [comment]
@ezequias and @TimPeters You might be interested in how we have utilized calcite maps with CMV, the configurable map viewer. The implementation has a full layer list for 3.x as well as many other widgets. Support for 4.x is coming soon. I provided a more detailed answer in issue #150. The repo is available [here](https://github.com/cmv/cmv-calcite-maps).

**Comment by ezequias** [comment]
I really love it @tmcgee great work. Does it have any kind of licensing?
