### ISSUE TITLE
Dojox charting in popup

### ISSUE THREAD

**Issue by TimPeters** [Esri/calcite-maps#156]
Hy @alaframboise ,

I applied the Calcite Maps theme on a ESRI [tutorial for dojox charts](https://developers.arcgis.com/javascript/3/sandbox/sandbox.html?sample=widget_infowindowchart).
The only structural change I did to the tutorial was to deactivate the infoWindow and use the popup:
```
        // Use the info window instead of the popup.
        // var infoWindow = new InfoWindow(null, domConstruct.create("div"));
        // infoWindow.startup();

        map = new Map("map", {
          basemap: "streets",
          center: [-113.405, 43.521],
         // infoWindow: infoWindow,
          zoom: 6
        });

       // map.infoWindow.resize(275, 275);
```

But the popup returns an error, it doesn't seem to be using it's full height:

![c1](https://cloud.githubusercontent.com/assets/26526622/24307935/b45e51f6-10ce-11e7-9c35-4b9d89dbaa05.jpg)

The result is available on [JS Bin](http://jsbin.com/bafogicihe/1/edit?html,output).
Is this a compatibility issue with Calcite Maps? 
Can it be fixed?

My goal is to learn to integrate dojox charts in Calcite Maps.

Thank you,
Tim.

**Comment by alaframboise** [comment]
I believe you need claro.css for charts to work in popups, but it should be easy to just style the popup however to show the taller content.

```
    
    <style>
      html, body, #map {
        height: 100%;
        width: 100%;
        margin: 0;
        padding: 0;
      }
      .chart {
        width:200px;
        height:200px;
        padding:0px !important;
      }
      
      .esriPopup .contentPane {
        height: 250px;
      }
    </style>
```

![image](https://cloud.githubusercontent.com/assets/2539681/24316230/ffcbdf40-10b1-11e7-81f6-7fbe00e3579f.png)

**Comment by TimPeters** [comment]
`<link rel="stylesheet" href="https://js.arcgis.com/3.20/dijit/themes/claro/claro.css">` 
doesn't seem to have any effect, but  `.esriPopup .contentPane {height: 250px;}`  does the trick.

Thank you @alaframboise !
