### ISSUE TITLE
Dock Popup

### ISSUE THREAD

**Issue by TimPeters** [Esri/calcite-maps#157]
Hi Allan,

I am using popups and the Measurement widget in Calcite Maps 3.20.
This combination seems not to be working because every time you click to create a measurement the popup appears and covers your region of interest.

I guess the solution is to dock the popups but that is only available in Calcite Maps 4.x.
The [Popup widget](https://developers.arcgis.com/javascript/latest/api-reference/esri-widgets-Popup.html) with ` dockEnabled:true`  is not available in JavaScript 3.x.

Still, your panels in Calcite Maps 3.20 are docked and also beautiful responsive.

Is there a way to make the popups behave like the panels in Calcite Maps 3.20 ?

Thank you,
Tim

**Comment by alaframboise** [comment]
@TimPeters at 3.x I might try putting the popup in a panel in mobile view. See

https://developers.arcgis.com/javascript/3/jssamples/popup_sidepanel.html

**Comment by TimPeters** [comment]
Thank you Allan
