### ISSUE TITLE
Jquery Version throwing an error

### ISSUE THREAD

**Issue by Jfairfield1** [Esri/calcite-maps#159]
After including the jquery version of the build for calcite maps, I am getting this error 
`panels.collapse is not a function`

It is occurring on line 40
`panels.collapse("hide");`

**Comment by alaframboise** [comment]
Can you provide a repo case? I just ran [this jQuery sample](http://esri.github.io/calcite-maps/samples/arcgis-4.x/arcgis-4.x-2d-3d-jQuery.html) and it seems work as expected. Thanks.

**Comment by Jfairfield1** [comment]
I created a jsbin example showing the error I am talking about:

https://jsbin.com/xidohezuga/edit?html,output

If you load this jsbin and try to toggle the basemap panel, it throws the error.

**Comment by alaframboise** [comment]
You are mixing and match jQuery and the dojo loader.

Here's an example using dojo to load bootstrap and calcite-maps and jQuery is loaded at the end. https://jsbin.com/damafe/edit?html

This one loads dojo just for ArcGIS and then jQuery for bootstrap and calcite-maps.
https://jsbin.com/zowizeq/edit?html

Closing.
