### ISSUE TITLE
How to set 2D vs 3D view nav and panes at startup

### ISSUE THREAD

**Issue by lance-weaver** [Esri/calcite-maps#160]
Seems like setting the default view should be easy.. but I cant figure it out.

setting app.activeView = app.mapView;  or  app.activeView = app.sceneView;  doesn't work for me on any of the examples.

How do you change the default view between mapview and sceneview?

**Comment by alaframboise** [comment]
You need to activate the tab pane. This should do it for you.

http://jsbin.com/tajupoq/edit?html,output

**Comment by lance-weaver** [comment]
Thanks for the quick reply.

And just to clarify for future users....   look for the following HTML code, and switch the classes "fade in active" between the 3D and 2D tab id's.

<div class="calcite-map calcite-map-absolute">
    <div id="tabContainer" class="tab-content">
      <div id="2dTab" class="tab-pane fade in active" role="tabpanel">
         <div id="mapViewDiv"></div>
      </div>
      <div id="3dTab" class="tab-pane fade" role="tabpanel">
        <div id="sceneViewDiv"></div>
      </div>
    </div>
  </div>

**Comment by alaframboise** [comment]
Yes, you basically need to update the app state: nav menus, panes and view variables. I'll update the title of this if that's ok and close it out. Thanks.

**Comment by alaframboise** [comment]
Closing.
