### ISSUE TITLE
Panel titles of accordion aren't showing

### ISSUE THREAD

**Issue by kikillotest** [Esri/calcite-maps#162]
I made an accordion of 4 panels and each time i switch to a panel, only this panel title is shown, others are masked

**Comment by alaframboise** [comment]
If you are using calcite-panels, that's how they work. If you want the standard bootstrap accordion behavior, just remove calcite-panels. That should work for you.

**Comment by kikillotest** [comment]
hi,
sorry i'm late to answer (AFK : birth of my son)
removing that class helped, thanks
