### ISSUE TITLE
page load with Info Panel open?

### ISSUE THREAD

**Issue by jjhi11** [Esri/calcite-maps#164]
I'm trying with jQuery but nothing I try will trigger it.

This is the best I can come up with.

$(document).ready(function() {
    $('.dropdown-menu a[data-target="#panelInfo"]').trigger('click');
});

**Comment by alaframboise** [comment]
@jjhi11 Hi there, do want to do this via HTML/CSS or JS? If HTML, all you need to do is set the panel and menu as active and in to load with the panel.  See this example: https://jsbin.com/zowizeq/edit?html,output

**Comment by alaframboise** [comment]
If you want to do it programmatically try this: https://jsbin.com/qulurov/edit?html,output

**Comment by jjhi11** [comment]
Thanks Allan!

**Comment by alaframboise** [comment]
No problem. Closing.

**Comment by MichelleJean28** [comment]
Hi Allan,
I am having the same issue. And I don't quite understand how to replicate your examples above for a Info Panel that should be opened when loading the page.
Here is your arcgis-3.x sample code: [JS BIN](http://jsbin.com/coculehiti/1/edit?html,output)
Could you please provide a code for this arcgis-3.x map on how to activate the Panel Info?

Thank you,
Michelle.

**Comment by alaframboise** [comment]
@MichelleJean28 Here is the code that is opening in the panels programmatically.

```
$(document).ready(function() {
        $('#panelBasemaps, #collapseBasemaps').collapse('show');
      });

``` 

But this is only if you need to do this programmatically. The standard (and easier way) is to use the `in` class. See examples.

**Comment by MichelleJean28** [comment]
Thank you Allan :)
