### ISSUE TITLE
Set location

### ISSUE THREAD

**Issue by uZuRu17** [Esri/calcite-maps#165]
Hi ,
First of all , Im new to this , so I might  post this into the wrong place, feel free to delete/move or what ever there needs to be done (altrought I would apreciate if someone would tell me what I did wrong and how to fix it).
That aside, I find the Set location option limited, at least for my needs.
Im trying to use it as a way to find the location of an organisation.
Problem is that the  start-up location cant be found with the search option.
(I dont know anything about the location data base so there might be a place where I can add the location I need, or a way to search coordonates).
Thank you for your time.

**Comment by alaframboise** [comment]
HI @uZuRu17. I'm not clear on the question. If you know the lat/lon, you can always set the map location on startup like this.

```
      var mapView = new MapView({
        container: "mapViewDiv",
        map: map,
        center: [-40, 40],
        zoom: 2
      });
```

What API are you using? Can you share a jsBin with your example?
