### ISSUE TITLE
Using with ol

### ISSUE THREAD

**Issue by am2222** [Esri/calcite-maps#166]
Hi,
Is it possible to use these layouts for openlayers? Does it need any changes?and it it need can you please give me some hint about doing so?
thanks very much

**Comment by alaframboise** [comment]
You should be able to use Calcite-Maps with any mapping framework. Just add the div to the .calcite-map container.

```
<!-- Map  -->

  <div class="calcite-map calcite-map-absolute">
    <div id="mapViewDiv"></div>
  </div>
  <!-- /.calcite-map -->

```

**Comment by am2222** [comment]
Thanks very much
