### ISSUE TITLE
calcite-search-expander auto collapsing

### ISSUE THREAD

**Issue by PaulYoum** [Esri/calcite-maps#169]
When clicking to get focus or mousing over the calcite-search-expander with the esri search widget, I'm expecting the expansion to not shrink once the mouse leaves on mouseout. Looking at the source:

[https://github.com/Esri/calcite-maps/blob/22aed6043cd7492c03a0271084d8f92e2c61e5cc/lib/sass/support/arcgis-4.x.scss#L290-L315](url)

or
[https://github.com/Esri/calcite-maps/blob/22aed6043cd7492c03a0271084d8f92e2c61e5cc/lib/sass/support/arcgis-4.x.scss#L366-L396](url)

I'm not expecting this behavior to occur, but it still is.

**Comment by alaframboise** [comment]
Ya I've been thinking about enabling click instead of mouse in/out. It will require a coding solution however. The current implementation is 100% css.

**Comment by alaframboise** [comment]
@PaulYoum another solution is to just remove the expand css class altogether.

`calcite-search-expander`
