### ISSUE TITLE
The legend in scene doesn't display layers.

### ISSUE THREAD

**Issue by bfener** [Esri/calcite-maps#170]
When a legend widget with legend panel was added to project, the legend don't display layers in scene panel. The layers  appear only in legend panel in map.

**Comment by alaframboise** [comment]
Sounds like a core JS issue. You might want to post something here:

https://geonet.esri.com/community/developers/web-developers/arcgis-api-for-javascript

**Comment by alaframboise** [comment]
Closing this is not a Calcite Maps issue.
