### ISSUE TITLE
Sublayers in WidgetList

### ISSUE THREAD

**Issue by sarojthapa60** [Esri/calcite-maps#171]
In ArcGIS api for javascript 4.4, I was using sublayers inside MapImageLayer to enable popups. This messes up with the layerlist and hence the layerlist widget does not honor sublayers. However, if I do not use sublayers inside the MapImageLayer, the layerlist honors the sublayers.

**Comment by alaframboise** [comment]
I believe this is an ArcGIS JS 4 issue. I would log it with the team. Thanks.
