### ISSUE TITLE
Mobile menu

### ISSUE THREAD

**Issue by MichelleJean28** [Esri/calcite-maps#172]
Hi Allan,
Since most people are right-handed the mobile menu button would be much more accessible if placed on the right side. As it is placed now on the left it is more difficult to reach with the same hand, especially on phones with larger screens.
Below a print screen example how a menu looks with the menu button on the right side. 
Could you provide some css lines on how to properly make such a change?

Thank you,
Michelle

![print screen](https://user-images.githubusercontent.com/25815540/29489826-609cb5d4-8532-11e7-8f2e-4f8abe14ac47.jpg)

**Comment by apatriz** [comment]
It looks like there are a couple classes (.right, .calcite-right) that can be added to the 'calcite-dropdown' div to switch the menu to the right. So in your index.html page, the dropdown menu toggle div might look like: 
`<div class="dropdown calcite-dropdown right calcite-right calcite-bg-light calcite-text-dark" role="presentation">`

I tested this and had some issue with the drawer position, so it might need some tweaking

**Comment by MichelleJean28** [comment]
Hi @apatriz 
Working great, thank you :)
