### ISSUE TITLE
switching between 2d and 3d causes map rotation

### ISSUE THREAD

**Issue by weaverk** [Esri/calcite-maps#173]
there is a slight rotation of the map anticlockwise when you flip from 3d to 2d, doing this repeatedly can result in quite noticeable deviation of the 2 map from the 'conventional' expectation of north = straight up 

http://esri.github.io/calcite-maps/samples/arcgis-4.x/arcgis-4.x-2d-3d.html

a small deviation attached to see the issue.

![image](https://user-images.githubusercontent.com/973894/29620262-bea70542-881d-11e7-8322-d3d887a3b1ef.png)

**Comment by alaframboise** [comment]
Ya, there are better ways to share the viewpoint, rotation... between views. I'll fix this in the sample.

**Comment by alaframboise** [comment]
I've updated the sample and there shouldn't be any rotation now.
