### ISSUE TITLE
Bootstrap Modal

### ISSUE THREAD

**Issue by PaulYoum** [Esri/calcite-maps#174]
Currently it appears that the bootstrap modal component isn't working with Calcite. Are there any future plans for modal support with Calcite? Is there anything modal-like that's compatible currently?

**Comment by PaulYoum** [comment]
I simply went to bootstrap and customized my download of bootstrap to include the modal part only and it works like a charm:
https://getbootstrap.com/docs/3.3/customize

**Comment by mgleahy** [comment]
I'm having problems with this too...maybe it's actually working fine, but it doesn't appear right to me.  I can get a modal sort-of working: open up any of the JSAPI/dojo based samples, and run this code in the console:

```js
require(['dojo/query', 'bootstrap/Modal'], function(query){
 
  query('body').append('<div class="modal" id="myModal"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="myModalLabel">Modal header</h3></div><div class="modal-body"><p>Modal body</p></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Close</button></div></div>');

  query('#myModal').modal();

});
```

It _works_, but the styling seems off.  Same thing happens in the leaflet/jquery demo:

```js
$('body').append('<div class="modal" id="myModal"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button><h3 id="myModalLabel">Modal header</h3></div><div class="modal-body"><p>Modal body</p></div><div class="modal-footer"><button class="btn" data-dismiss="modal" aria-hidden="true">Close</button></div></div>');

$('#myModal').modal();
``` 

Is the current appearance/behaviour of the bootstrap modals in calcite-maps expected?
