### ISSUE TITLE
Image services in web maps do not retain configuration properties

### ISSUE THREAD

**Issue by twnawrocki** [Esri/calcite-maps#178]
The calcite maps app framework does not respect the configuration of image services when using an arcgis online web map or a json web map. Image services from the web map do not retain the styling applied in the web map and instead default to a server rendering.

Other app frameworks, such as the basic viewer and web app builder do respect the configuration of the web map so I suspect the javascript API is not the root of the problem.

You can see an example of this problem by comparing this [web map](https://arcg.is/0DXLuf), which pulls in two image services with style configuration, to a [calcite application](http://accs.uaa.alaska.edu/mapping/landcoverofalaska.html) referencing the same web map as json (the same result occurs when referencing the web map from arcgis online directly by id). The image services appear in the calcite application but without the style configuration applied in the web map.

**Comment by alaframboise** [comment]
Hi @twnawrocki I believe this is a limitation or an issue with the ArcGIS JS 4.x API. If you load the webmap in this sample you get the same behavior.  https://developers.arcgis.com/javascript/latest/sample-code/sandbox/index.html?sample=webmap-basi
