### ISSUE TITLE
Issue with basemap toggle z index

### ISSUE THREAD

**Issue by Jfairfield1** [Esri/calcite-maps#179]
This css line:

```
.esri-widget-button {
    z-index: 1
}
```
Seems to be causing an issue when using esri's basemap toggle widget.  The map appears on top of the widget like this:

![image](https://user-images.githubusercontent.com/13153086/33458517-b9817ad4-d5e3-11e7-8be0-cb445fa1fb5e.png)

_*Note: I am using ArcGIS API for JavaScript Version 4.5_

**Comment by alaframboise** [comment]
Hey @Jfairfield1 , would you mind creating a jsBin for this? I tried the default example and it seems to work ok.  http://jsbin.com/fogiyos/edit?html,output

**Comment by Jfairfield1** [comment]
Here is a jsbin:

http://jsbin.com/rexudakodo/1

I guess I have some custom css in my project that was making it act funny.

This line seems to mess up the basemap:

`    .esri-widget.esri-widget-button {
        border-radius: 5px;
    }`

**Comment by alaframboise** [comment]
@Jfairfield1 thanks! I have a fix for this and all z-index issues that I'll push up.

**Comment by Jfairfield1** [comment]
@alaframboise Awesome!  Thanks so much for your quick response!

**Comment by alaframboise** [comment]
Fixed in v.06
