### ISSUE TITLE
Directions Widget in Calcite Panel: search z-index and .esri-widget-button sizing

### ISSUE THREAD

**Issue by dcoley** [Esri/calcite-maps#181]
Hi Alan - 
For the Directions widget, seems there are a couple of issues when placed into a calcite panel.  First, the z-index for the suggestions menu in the upper esri-search container will display below the lower search esri-search container.  I was able to get around it by un-setting the z-index in my override.css:

.calcite-maps .esri-basemap-toggle, .calcite-maps .esri-search .esri-search__container {
    z-index: unset;
}
Second, the current css settings for the esri-widget-button class are forcing the Directions widget date picker to the left:

.calcite-maps .esri-widget .esri-widget-button, .calcite-maps .esri-widget.esri-widget-button {
    width: 30px;
    height: 30px;
    font-size: 13px;
}

![image](https://user-images.githubusercontent.com/5313604/34797565-c7fcef9a-f626-11e7-85f3-072d87187c9b.png)

I can't quite seem to be able to get around the second issue yet-
Thanks,
David

**Comment by alaframboise** [comment]
I put a quick fix in for v0.6.

**Comment by dcoley** [comment]
Yeah thanks Alan, looks great. Both issues appear resolved.
