### ISSUE TITLE
Popover css

### ISSUE THREAD

**Issue by crackernutter** [Esri/calcite-maps#185]
I can't seem to find the Popover css anywhere in this repo, although the Popover.js is present.  I had to copy the css from Twitter Bootstrap to my local css to get Popover to work when using calcite-maps-bootstrap.  Is this intended, or am I missing something?

**Comment by alaframboise** [comment]
You need to uncomment the popover.js in the bootstrap build and run grunt.

https://github.com/Esri/calcite-maps/blob/master/lib/sass/bootstrap-components.scss
