### ISSUE TITLE
Apply license headers to dist and CDN

### ISSUE THREAD

**Issue by gisdev-km** [Esri/calcite-maps#186]
Similar to the efforts in calcite-web, can we get the license header affixed in dist/ and also a summarized license attached to the CDN file?

Related calcite-web issue: https://github.com/Esri/calcite-web/issues/841

Example of summarized license from materiali-lite: https://code.getmdl.io/1.3.0/material.min.js

**Comment by alaframboise** [comment]
This should be handled now in v0.9.
