### ISSUE TITLE
Top of Widget panels get hidden under Nav bar in main sample 

### ISSUE THREAD

**Issue by pcsswamin** [Esri/calcite-maps#190]
Top of widget panels get hidden under the nav bar in main code  sample  whose code is displayed on https://github.com/Esri/calcite-maps. so for example, user cannot close or see the title of widget panel such as legend or basemap.

**Comment by alaframboise** [comment]
Not able to repro can you provide a jsbin or codepen?

**Comment by pcsswamin** [comment]
from the sample I copied out yesterday. Here is a jsbin...only changes like title by me...
https://jsbin.com/jawudizisi/1/edit?html,output 

I cannot reproduce with your 4.7 sample today. Would be interested to know what caused it.

**Comment by alaframboise** [comment]
You had `calcite-nav-margin-top` instead of `calcite-nav-top` in your code. 4.6 and 4.7 work the same. Thanks.
