### ISSUE TITLE
Font error

### ISSUE THREAD

**Issue by ej-asuzuki** [Esri/calcite-maps#197]
Calcite maps try to load fonts from wrong place and return 404 error.
I took an error capture.

![error](https://user-images.githubusercontent.com/12059203/37444508-4fe46aae-2855-11e8-9054-135dd29333d1.png)

It seems that the referenced files are not provided when I ckeced dist/fonts/avenir-next folder.

You can check the error when you open the sample Esri provided.
- https://developers.arcgis.com/javascript/latest/sample-code/frameworks-bootstrap/

I am not famillier with web font.
So I am not sure if I need any additional settings to use these fonts.
However I think it is necessary to provde these fonts.

**Comment by alaframboise** [comment]
All of the fonts are in the dist directory and there I do not see any font errors on this side.  
https://github.com/Esri/calcite-maps/tree/master/dist/fonts/

The SDK sample is currently being updated with the JS 4.7/0.7 release of calcite-maps. Please see the examples included.
