### ISSUE TITLE
map.View is not a function

### ISSUE THREAD

**Issue by elake2018** [Esri/calcite-maps#207]
Uncaught TypeError: mapView.then is not a function
    at (index):188
    at K (dojo.js:18)
    at dojo.js:19
    at E (dojo.js:19)
    at ea (dojo.js:19)
    at g (dojo.js:21)
    at HTMLScriptElement.<anonymous> (dojo.js:23)

I simply copy and pasted the code page "Example" from the home page here. Map showed up with trail or road data whatever the lines are.

**Comment by acrateau** [comment]
Change the method from .then to .when.  This change was implemented starting with the 4.7 version of the js api.

**Comment by alaframboise** [comment]
Thanks! fixed  https://github.com/Esri/calcite-maps/pull/210
