### ISSUE TITLE
Missing icon when using ArcGIS API 4.8

### ISSUE THREAD

**Issue by jessevarner** [Esri/calcite-maps#208]
Hi, I noticed that at least some of the button icons are missing when you use Calcite with ArcGIS API for JavaScript 4.8. For example, the search icon in the upper-right is missing on this page:
https://developers.arcgis.com/javascript/latest/sample-code/frameworks-bootstrap/index.html

If I switch the API back to version 4.7, the icon appears correctly.

**Comment by alaframboise** [comment]
should be good in the latest build
