### ISSUE TITLE
Hooking into search for custom popup

### ISSUE THREAD

**Issue by Wylisc** [Esri/calcite-maps#220]
So I am trying to create a custom popup when a search result is selected, but I am unable to hide the built in search popup with the following code:

`
var searchWidget = new Search({
        view: view,
        popupOpenOnSelect: false
      });
      
      searchWidget.on('select-result', function(evt){
        console.info(evt);
        view.popup.open({
         location: evt.result.feature.geometry,  // location of the click on the view
         title: evt.result.name,  // title displayed in the popup
         content: evt.result.extent.center.latitude + " , " + evt.result.extent.center.longitude // content displayed in the popup
        });
      });
`

Specifically the popupOpenOnSelect function isn't being registered and thus the default popup remains. Using ArcGIS api sandbox without calcite and it works as intended so I think something in calcite might be overriding the setting and displaying it anyways.

Any insight into this matter would be greatly appreciated :)

**Comment by alaframboise** [comment]
You don't need a new search, you need to get the search the app creates. It's in the ViewManager.js. Try applying that code there.

**Comment by Wylisc** [comment]
Sorry I'm new at this, but where is ViewManager.js?

**Comment by Wylisc** [comment]
> You don't need a new search, you need to get the search the app creates. It's in the ViewManager.js. Try applying that code there.

Basically what I've done is take the Example from the front page and I have been testing that.
