### ISSUE TITLE
Add CHANGELOG

### ISSUE THREAD

**Issue by paulcpederson** [Esri/calcite-maps#32]
Recommend using SEMVER and adding a `CHANGELOG.md` that formatted like http://keepachangelog.com/ (which is pretty standard). 

This project would also be a great candidate for GitHub releases, which would make finding and downloading a particular version really easy.

**Comment by alaframboise** [comment]
Yes, will do. Thanks!

**Comment by alaframboise** [comment]
Done! https://github.com/Esri/calcite-maps/releases/tag/v0.0.1
