### ISSUE TITLE
Loading template

### ISSUE THREAD

**Issue by andygup** [Esri/calcite-maps#33]
Consider implementing a UI loading template or [overlay pattern](https://dojotoolkit.org/documentation/tutorials/1.10/loading_overlay/). 

This will help manage user perception up to the point where map tiles finish loading. Most folks won't be able to implement top-of-the-line performance and caching measures. 

During some rough performance testing at 3G speeds the [esri-leaflet](http://esri.github.io/calcite-maps/demos/esri-leaflet.html) demo was taking ~4.5 seconds before all tiles finished loading. The [dojo-starter](http://esri.github.io/calcite-maps/demos/arcgis-dojo-starter.html) was showing ~4.5 seconds before the first tile loads and in most cases over 10 seconds until the final tile loaded.

**Comment by alaframboise** [comment]
Calcite-Bootstrap has a great "is loading" indicator that could be implemented. This is definitely more of app-level implementation rather than a framework implementation but could be considered. Thanks.

**Comment by alaframboise** [comment]
https://github.com/Esri/calcite-maps-styler-template has a loader indicator implemented that could be used.
