### ISSUE TITLE
Consider removing arcgis-content jpg's

### ISSUE THREAD

**Issue by andygup** [Esri/calcite-maps#34]
When the leaflet sample runs it loads the following jpg's. Are they required or can they be removed? I didn't sleuth into where the images were coming from, I just noticed them slowing down the load time: 

http://www.esri.com/~/media/Images/Content/data/graphics/arcgis-content/main-basemaps.jpg
http://www.esri.com/~/media/Images/Content/data/graphics/arcgis-content/main-demographics.jpg

**Comment by JeffJacobson** [comment]
It looks to me like they're being used in the *Bookmarks* Panel. (As for what this panel is **actually supposed to do** other than show these images: I have no idea.)

**Comment by alaframboise** [comment]
Bookmarks is just an example of how to insert a carousel into a panel. The carousel requires images so I just grabbed those. They will be removed in the beta2/3 update. Thanks.

**Comment by alaframboise** [comment]
Removed in next release.
