### ISSUE TITLE
HTML comments inside of JavaScript

### ISSUE THREAD

**Issue by JeffJacobson** [Esri/calcite-maps#35]
In the demo HTML files, there are `<!-- HTML comments -->` within the `<script>` tags, when they should be `// JavaScript comments`.

This:
```javascript
		$(document).ready(function(){
                    // Do something
		});<!-- jQuery -->
```
...should be this:
```javascript
		$(document).ready(function(){
                    // Do something
		}); // <!-- jQuery -->
```

Examples:
* https://github.com/Esri/calcite-maps/blob/master/demos/arcgis-dojo-starter-3.x.html#L219
* https://github.com/Esri/calcite-maps/blob/master/demos/arcgis-jquery.html#L699

**Comment by alaframboise** [comment]
Yes, this will all be addressed in beta2-3 updates. Thanks.

**Comment by alaframboise** [comment]
All fixed, thanks.
