### ISSUE TITLE
Calcite-Maps ArcGIS JS 4.0 Dojo does not show a map using IE 11

### ISSUE THREAD

**Issue by gisfromscratch** [Esri/calcite-maps#36]
I am using IE Version 11.0.9600.18124.
The map is not showing and no error is logged to the console.

Using the JS 3.x version works fine for me.

**Comment by alaframboise** [comment]
Ok thanks! Lots of churn in the 4.0 API right now and I'll make sure everything is solid for beta3/final.

**Comment by alaframboise** [comment]
Tested in IE and all is well. Closing.
