### ISSUE TITLE
How to open app in Map View

### ISSUE THREAD

**Issue by slead** [Esri/calcite-maps#74]
Awesome app, thanks so much for creating and sharing this.

I'm struggling with how to open the app in Map View.

Taking the [sandbox example](https://developers.arcgis.com/javascript/latest/sample-code/sandbox/sandbox.html?sample=frameworks-bootstrap), changing line 299 to `app.activeView = app.mapView;` has no effect - the app still opens in Scene View.

The code at line 392 (`// Toggle map and scene`) does correctly change the mode - is there an event which needs to fire before `app.activeView = app.mapView` will work?

Or is there another way to open the app in Map View?

**Comment by dmartine** [comment]
You also need to update the div class for mapcontainer to the following:
 <div id="2dTab" class="tab-pane fade in active" role="tabpanel">
   
      <div id="3dTab" class="tab-pane fade" role="tabpanel">

**Comment by dmartine** [comment]
You also need to update div class for mapcontainer.  2dTab class="tab-pane fade in active" and 3DTab class="tab-pane fade". This will open in the map view.
