### ISSUE TITLE
Export Styler settings

### ISSUE THREAD

**Issue by andygup** [Esri/calcite-maps#92]
It would be super useful if:

1) the Theme and Layout settings in the Settings widget could be exported as CSS for use in another app.

2) all the settings could be saved locally and the read automatically on app restart.

**Comment by alaframboise** [comment]
Yip, I've got some prototypes for this that export the JSON and load it. I'm kinda waiting however because I might just put that info in a webmap.

**Comment by alaframboise** [comment]
You can use the share tool now in https://github.com/Esri/calcite-maps-styler-template to get the json for your current config. Not quite export but it is there.
